import { OPENAI_MODELS } from '../adapters'
import { AppSchema } from '../types/schema'

export const koboldPresets = {
  basic: {
    service: 'kobold',
    name: 'Simple',
    maxTokens: 300,
    maxContextLength: 2048,
    repetitionPenalty: 1,
    repetitionPenaltySlope: 1,
    repetitionPenaltyRange: 1024,
    temp: 0.8,
    topK: 0,
    topP: 1,
    minP: 0.1,
    typicalP: 1,
    topA: 0,
    tailFreeSampling: 1,
    encoderRepitionPenalty: 1.0,
    penaltyAlpha: 0,
    addBosToken: true,
    banEosToken: false,
    skipSpecialTokens: true,
    order: [0, 1, 2, 3, 4, 5, 6],
    frequencyPenalty: 0,
    presencePenalty: 0,
    gaslight: '',
    ultimeJailbreak: '',
    oaiModel: OPENAI_MODELS.Turbo,
    streamResponse: false,
    memoryDepth: 50,
    memoryContextLimit: 500,
    memoryReverseWeight: false,
    antiBond: false,
  },
} satisfies Record<string, Partial<AppSchema.GenSettings>>
