name: Web deploy

on:
  push:
    branches: ['dev']

env:
  IMAGE_NAME: agnaistic
  node-version: '18.4.0'
  pnpm-version: 8.6.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node and PNPM
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Get cached dependencies
        # cache is automatically saved after this job completes. jobs depending on this one will get the latest cached files
        id: cache-step
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install project dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          ls -la
          echo $NODE_ENV
          pnpm install --frozen-lockfile

      - name: Build frontend
      env:
          INJECT_SCRIPT: ${{ secrets.INJECT_SCRIPT }}
        run: |
          pnpm run build:prod
          cp dist/index.html dist/original.html
          node .github/inject.js

      - name: Publish - Live
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_ASSET_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.S3_ASSET_SECRET_KEY }}
          aws_bucket: ${{ secrets.S3_PRD_ASSET_BUCKET }}
          source_dir: 'dist'
          destination_dir: ''
